tunnel: vvz-core
credentials-file: ~/.cloudflared/975af37c-74a5-4995-992e-e9b0dba02322.json

ingress:
  - hostname: logline.voulezvous.tv
    service: http://127.0.0.1:7613
  - service: http_status:404

originRequest:
  noTLSVerify: true
  connectTimeout: 5s
